### ISSUE TITLE
NStore.Persistence.MsSql/0.2.0-sqlitebinary0111 nuget package is failing to install with obscure error

### ISSUE THREAD

**Issue by mauroservienti** [ProximoSrl/NStore#65]
The following nuget package fails at install time https://www.nuget.org/packages/NStore.Persistence.MsSql/0.2.0-sqlitebinary0111

What seems indeed weird is the package name suffix containing `sqlitebinary`

**Comment by mauroservienti** [comment]
let me amend the above comment, the actual error I get is:

> Unable to find package NStore.BaseSqlPersistence. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org

**Comment by mauroservienti** [comment]
Cool, thanks @alkampfergit. Does it mean that it’s better to use a previously released package to play with NStore?

**Comment by alkampfergit** [comment]
@mauroservienti I've just published on nuget, right now, the 0.2.1-beta002 package, this is the version we are actually using in production with some small fix.

I strongly suggest you to use this or develop to play with NStore, these are the almost stable build, feature builds can have experimental code that is subjected to rapid change.

Feel free to ping me in private :).

Alk.

**Comment by mauroservienti** [comment]
Thanks, I’ll update.
