### ISSUE TITLE
What do I need to support aggregates with non default constructors?

### ISSUE THREAD

**Issue by mauroservienti** [ProximoSrl/NStore#66]
Say that I have an aggregate like the following:

```
public class Person : Agregate<PersonState>
{
   public class PersonState{}

   public Person(string name){} //used when initializing new Person instances

   private Person(){} //used by infrastructure when loading aggregate from persistence 
}
```

Questions:

* In order to support it do I need a custom aggregate factory?
* Can I `Emit` An event in the public constructor? Such as `PersonCreated` event.
* Do I need to call `Init` To set the ID or if not called it’ll be done automatically by infrastructure?

**Comment by alkampfergit** [comment]
Actually we have in Jarvis aggregates with no default constructor, we have a factory that use default constructor or uses Castle.Windsor to resolve with optional external services.

We never have initialization in constructor with some properties that have business meaning. In your example you have a 

`public person(string name)`

And we would never have such constructor in an aggregate, we will use the default aggregate and then call some method like SetName, or whatever. In such a situation some of the events should be raised in the constructor, and is a situation we do not want to handle. The constructor is there only to inject external dependencies and nothing related to business or something that should raise events.

The init is called by the repository, the situation we have is that no aggregate is created outside of the repository (except for testing).

You can always use a custom aggregate factory if you really need to use some special constructors.

Alk.

**Comment by mauroservienti** [comment]
If I do something like this:

```
var p = new Person();
p.SetName("mauro");
```

where `SetName` is defined as:

```
public void SetName(string name)
{
   Emit(new NameChanged( name ));
}
```

and `PersonState` is as:

```
public class PersonState
{
   private void On(NameChanged @event){ ... }
}
```

A `NRE` is thrown, inspecting with the debugger the aggregate `State` protected property is null, looking at source code `State` is instantiated only when `Init` is called. Thus the question, do I need to manually call `Init`.

**Comment by mauroservienti** [comment]
I think I understood, a call to `Repository.GetByIdAsync<TAggregate>` is mandatory, if the aggregate doesn't exist it'll be created and returned to the caller, initialized.

**Comment by alkampfergit** [comment]
Yes.

Il 23 dic 2017 14:38, "Mauro Servienti" <notifications@github.com> ha
scritto:

**Comment by mauroservienti** [comment]
Thanks
